version: '3'

dotenv: ['.env']

tasks:
  ##############################
  ### TESTS
  ##############################
  test:
    cmds:
      - uv run pytest {{.CLI_ARGS}}
    desc: Run pytest
    aliases: [t]
  test:watch:
    cmds:
      # ptw crashes without this fix, ] must be indented
      - sed -i '' 's/^]$/    ]/' pyproject.toml
      - uv run ptw -- {{.CLI_ARGS}}
    desc: Run pytest-watch
    aliases: [tw]
  test:coverage:
    cmds:
      - uv run pytest {{.CLI_ARGS}} --cov --cov-report=lcov:lcov.info --cov-report=term:skip-covered
    desc: Run pytest with coverage reporting
    aliases: [tc]
  test:watch-coverage:
    cmds:
      # ptw crashes without this fix, ] must be indented
      - sed -i '' 's/^]$/    ]/' pyproject.toml
      - uv run ptw -- {{.CLI_ARGS}} --cov --cov-report=lcov:lcov.info --cov-report=term:skip-covered
    desc: Run pytest-watch with coverage reporting
    aliases: [twc, tcw]
  ##############################
  ### LINT AND DEPENDENCIES
  ##############################
  lint:
    cmds:
      - uv run ruff check --fix
    desc: Run Ruff linter with auto-fix
    aliases: [l]
  lint-watch:
    cmds:
      - uv run ruff check --fix --watch
    desc: Run Ruff linter in watch mode with auto-fix
    aliases: [lw]
  lint-types:
    cmds:
      - uv run mypy {{.CLI_ARGS}}
    desc: Run mypy type checks
    aliases: [lt]
  upgrade-dependencies:
    desc: Upgrade all project dependencies to their latest compatible versions
    cmds:
      - uv sync --upgrade
    aliases: [ud]
  ##############################
  ### RELEASE DISPATCH
  ##############################
  publish:patch:
    cmds:
      - gh workflow run release.yml --ref main -f bump=patch
    desc: Dispatch the remote GitHub Actions patch release workflow [Usage] pp
    aliases: [pp]

  publish:minor:
    cmds:
      - gh workflow run release.yml --ref main -f bump=minor
    desc: Dispatch the remote GitHub Actions minor release workflow [Usage] pm
    aliases: [pm]
